// la data
var data = {
    "-M9pE1fS2pPwad5wCldg": {
        "categoria": "aseo",
        "descripcion": "5 en 1 vainilla +lavanda 2kg",
        "existencia": "disponible",
        "identificador": "-M9pE1fS2pPwad5wCldg",
        "nombre": "Detergente puro",
        "popular": "no",
        "precio": 10300,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3-sa-east-1.amazonaws.com/Detergente+puro07cc875a-3658-47b6-bf7a-8e57033bdeb5.jpg"
    },
    "-M9pGKBmXCaDkZ-AKU5j": {
        "categoria": "aseo",
        "descripcion": "Rindex 10 multibeneficios  2kg",
        "existencia": "disponible",
        "identificador": "-M9pGKBmXCaDkZ-AKU5j",
        "nombre": "Rindex detergente bicarbonato limón en polvo",
        "popular": "no",
        "precio": 9200,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3.amazonaws.com/Rindex%20detergente%20bicarbonato%20lim%C3%B3n%20en%20polvo16647a4d-8d87-49af-90d6-a013a6dba022.jpg"
    },
    "-M9pH8MtMNmx9ghGr-jF": {
        "categoria": "aseo",
        "descripcion": "1kg aroma floral fibraprotec",
        "existencia": "disponible",
        "identificador": "-M9pH8MtMNmx9ghGr-jF",
        "nombre": "Ultrex detergente",
        "popular": "no",
        "precio": 4500,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3.sa-east-1.amazonaws.com/-M9pH8MtMNmx9ghGr-jFKIP-PQP-DETER00937%28E%29.jpg"
    },
    "-M9pIbwqUZoCC5eIF3cI": {
        "categoria": "aseo",
        "descripcion": "10 multibeneficios bicarbonato limón 500 gramos",
        "existencia": "disponible",
        "identificador": "-M9pIbwqUZoCC5eIF3cI",
        "nombre": "Rindex detergente",
        "popular": "no",
        "precio": 2900,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3-sa-east-1.amazonaws.com/Rindex+detergente+en+polvo+500gr.jpg"
    },
    "-M9pJSQcJCMCCO0yDl4o": {
        "categoria": "aseo",
        "descripcion": "Rindex 10 multibeneficios bicarbonato frescura de suavizante 500 gramos",
        "existencia": "disponible",
        "identificador": "-M9pJSQcJCMCCO0yDl4o",
        "nombre": "Rindex detergente ",
        "popular": "no",
        "precio": 2900,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3-sa-east-1.amazonaws.com/Detergente+Rindex+500gr+suavizante+bicarbonato.jpg"
    },
    "-M9pKwnUq7DZXHrF8Hu6": {
        "categoria": "aseo",
        "descripcion": "Frescura de suavizante 2kg",
        "existencia": "disponible",
        "identificador": "-M9pKwnUq7DZXHrF8Hu6",
        "nombre": "Rindex detergente bicarbonato",
        "popular": "no",
        "precio": 9000,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3-sa-east-1.amazonaws.com/Rindex+detergente+bicarbonato+suavizante+2kg.jpg"
    },
    "-M9pLjnFQu3VNflfuX3N": {
        "categoria": "aseo",
        "descripcion": "By fab 850 gramos colores vivos y brillantes",
        "existencia": "disponible",
        "identificador": "-M9pLjnFQu3VNflfuX3N",
        "nombre": "Lavo matic  detergente",
        "popular": "no",
        "precio": 8050,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3-sa-east-1.amazonaws.com/Lavo+matic++detergente+850gramos.jpg"
    },
    "-M9pMiFoS4jzFTxVrowb": {
        "categoria": "aseo",
        "descripcion": "Fribraprotec aroma floral protege color y fibras 500 gramos",
        "existencia": "disponible",
        "identificador": "-M9pMiFoS4jzFTxVrowb",
        "nombre": "Ultrex detergente",
        "popular": "no",
        "precio": 2500,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3.sa-east-1.amazonaws.com/-M9pMiFoS4jzFTxVrowb09039-JABON-POLVO-ULTREX-FLORAL-500-GR.jpg"
    },
    "-M9pNZ1YFbuu2gnxhJDV": {
        "categoria": "aseo",
        "descripcion": "Fibraprotec aroma floral 250 gramos",
        "existencia": "disponible",
        "identificador": "-M9pNZ1YFbuu2gnxhJDV",
        "nombre": "Ultrex detergente",
        "popular": "no",
        "precio": 1400,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3.sa-east-1.amazonaws.com/-M9pNZ1YFbuu2gnxhJDVUltrex%20detergente.jpg"
    },
    "-M9pNxap1Kr0wH4eaTfK": {
        "categoria": "aseo",
        "descripcion": "Aroma floral 125 gramos ",
        "existencia": "disponible",
        "identificador": "-M9pNxap1Kr0wH4eaTfK",
        "nombre": "Ultrex detergente ",
        "popular": "no",
        "precio": 800,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3.sa-east-1.amazonaws.com/-M9pNxap1Kr0wH4eaTfKUltrex%20detergente%20.jpg"
    },
    "-M9pOy-slF6anoZxhPaV": {
        "categoria": "aseo",
        "descripcion": "Aroma de suavizante fresca manzana 100 gramos",
        "existencia": "disponible",
        "identificador": "-M9pOy-slF6anoZxhPaV",
        "nombre": "Las llaves detergente en polvo",
        "popular": "no",
        "precio": 1200,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3-sa-east-1.amazonaws.com/Las+llaves+detergente+en+polvo+100gr.jpg"
    },
    "-M9pPqP9oIp83-miLDdo": {
        "categoria": "aseo",
        "descripcion": "Aroma suavizante fresca manzana 200 gramos",
        "existencia": "disponible",
        "identificador": "-M9pPqP9oIp83-miLDdo",
        "nombre": "Las llaves detergente en polvo",
        "popular": "no",
        "precio": 2200,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3-sa-east-1.amazonaws.com/Las+llaves+detergente+en+polvo+100gr.jpg"
    },
    "-M9pQd68L3kvCpuHVgSZ": {
        "categoria": "aseo",
        "descripcion": "10 multibeneficios bicarbonato frescura de suavizante 125 gramos ",
        "existencia": "disponible",
        "identificador": "-M9pQd68L3kvCpuHVgSZ",
        "nombre": "Rindex detergente",
        "popular": "no",
        "precio": 900,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3-sa-east-1.amazonaws.com/Detergente+Rindex+suavizante+bicarbonato+125gr.jpg"
    },
    "-M9pRG2E5ai0gwPBo7Mx": {
        "categoria": "aseo",
        "descripcion": "Rindex multibeneficios bicarbonato limón 125 gramos",
        "existencia": "disponible",
        "identificador": "-M9pRG2E5ai0gwPBo7Mx",
        "nombre": "Rindex detergente bicarbonato limon",
        "popular": "no",
        "precio": 900,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3-sa-east-1.amazonaws.com/Rindex+detergente+bicarbonato+limon+125gr.jpg"
    },
    "-M9pRt18Gb60G2UMfUNH": {
        "categoria": "aseo",
        "descripcion": "Bicarbonato aloe vera 125 gramos",
        "existencia": "disponible",
        "identificador": "-M9pRt18Gb60G2UMfUNH",
        "nombre": "3D detergente multiuso",
        "popular": "no",
        "precio": 900,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3-sa-east-1.amazonaws.com/3D+detergente+multiuso+125gramos.jpg"
    },
    "-M9pTARWsXYhScR67IbO": {
        "categoria": "aseo",
        "descripcion": "Bicarbonato + aloe vera 250 gramos",
        "existencia": "disponible",
        "identificador": "-M9pTARWsXYhScR67IbO",
        "nombre": "3D multiuso detergente",
        "popular": "no",
        "precio": 1800,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3-sa-east-1.amazonaws.com/3D+multiuso+detergente250gramos.jpg"
    },
    "-M9pU3b_0yEat_agejIR": {
        "categoria": "aseo",
        "descripcion": "Rindex 10 multibeneficios bicarbonato y limón 250 gramos",
        "existencia": "disponible",
        "identificador": "-M9pU3b_0yEat_agejIR",
        "nombre": "Rindex detergente ",
        "popular": "no",
        "precio": 1800,
        "tipo": "unitario",
        "urlImagen": "https://prodsbucket.s3.sa-east-1.amazonaws.com/-M9pU3b_0yEat_agejIRRindex%20detergente%20.jpg"
    },
    "-M9pVrHxi38MUr5bcl-S": {
        "categoria": "licoreria",
        "descripcion": "Cerveza Águila original ",
        "existencia": "disponible",
        "identificador": "-M9pVrHxi38MUr5bcl-S",
        "nombre": "Cerveza Águila negra ",
        "popular": "no",
        "precio": 2000,
        "tipo": "unitario",
        "urlImagen": "https://firebasestorage.googleapis.com/v0/b/palmercao-3c01f.appspot.com/o/productos%2FCerveza%20%C3%81guila%20negra%20.jpg?alt=media&token=1a735330-9bd3-4339-8f28-3d9aaccb5bab"
    },
    "-MBBh9YCf4YeolCcmDUM" : {
        "categoria" : "frutas & verduras",
        "descripcion" : "",
        "existencia" : "disponible",
        "identificador" : "-MBBh9YCf4YeolCcmDUM",
        "nombre" : "Pimenton rojo",
        "popular" : "no",
        "precio" : 2500,
        "tipo" : "pesado",
        "urlImagen" : "https://prodsbucket.s3-sa-east-1.amazonaws.com/-APiment%C3%B3n+Rojo.jpg"
      },
      "-MBBhK7yTSufUg_oOW_h" : {
        "categoria" : "frutas & verduras",
        "descripcion" : "",
        "existencia" : "disponible",
        "identificador" : "-MBBhK7yTSufUg_oOW_h",
        "nombre" : "Pimenton verde",
        "popular" : "no",
        "precio" : 2000,
        "tipo" : "pesado",
        "urlImagen" : "https://prodsbucket.s3-sa-east-1.amazonaws.com/-APiment%C3%B3n+verde.jpg"
      },
      "-MBBhftcOzz6hT5mLo--" : {
        "categoria" : "frutas & verduras",
        "descripcion" : "",
        "existencia" : "disponible",
        "identificador" : "-MBBhftcOzz6hT5mLo--",
        "nombre" : "Naranja",
        "popular" : "no",
        "precio" : 250,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/-MBBhftcOzz6hT5mLo--Naranja.jpg"
      },
      "-MBBi2-u-kxYc6p5XV4K" : {
        "categoria" : "frutas & verduras",
        "descripcion" : "",
        "existencia" : "disponible",
        "identificador" : "-MBBi2-u-kxYc6p5XV4K",
        "nombre" : "Limón",
        "popular" : "no",
        "precio" : 200,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3-sa-east-1.amazonaws.com/-ALim%C3%B3n.jpg"
      },
      "-MBBiS44t6EdnGt9XA-k" : {
        "categoria" : "frutas & verduras",
        "descripcion" : "",
        "existencia" : "disponible",
        "identificador" : "-MBBiS44t6EdnGt9XA-k",
        "nombre" : "Apio",
        "popular" : "no",
        "precio" : 1500,
        "tipo" : "pesado",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/-MBBiS44t6EdnGt9XA-kApio.jpg"
      },
      "-MBBoA7VblDpcR_Fz339" : {
        "categoria" : "frutas & verduras",
        "descripcion" : "",
        "existencia" : "disponible",
        "identificador" : "-MBBoA7VblDpcR_Fz339",
        "nombre" : "Cebolla roja",
        "popular" : "no",
        "precio" : 1700,
        "tipo" : "pesado",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/-MBBoA7VblDpcR_Fz339Cebolla.jpg"
      },
      "-MBBqXRTuxzXX-rCFalP" : {
        "categoria" : "frutas & verduras",
        "descripcion" : "",
        "existencia" : "disponible",
        "identificador" : "-MBBqXRTuxzXX-rCFalP",
        "nombre" : "Yuca",
        "popular" : "no",
        "precio" : 700,
        "tipo" : "pesado",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/-MBBqXRTuxzXX-rCFalPYuca.jpg"
      },
      "-MCgrn3aoTixe6BzB36r" : {
        "categoria" : "aseo",
        "descripcion" : "5000 gramos fab azul",
        "existencia" : "disponible",
        "identificador" : "-MCgrn3aoTixe6BzB36r",
        "nombre" : "Fab especial 5 kilogramos detergente",
        "popular" : "no",
        "precio" : 24900,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.amazonaws.com/Fab%20especial%205%20kilogramos%20detergente.jpg"
      },
      "-MCgsMnggm9T20srU4qL" : {
        "categoria" : "aseo",
        "descripcion" : "6000 gramos fab azul",
        "existencia" : "disponible",
        "identificador" : "-MCgsMnggm9T20srU4qL",
        "nombre" : "Fab detergente 6 kilogramos",
        "popular" : "no",
        "precio" : 27500,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/Fab%20detergente%206%20kilogramos.jpg"
      },
      "-MCgvr_BvjN3cX8kwM_g" : {
        "categoria" : "aseo",
        "descripcion" : "4000 gramos dersa bicarbonato manzana",
        "existencia" : "disponible",
        "identificador" : "-MCgvr_BvjN3cX8kwM_g",
        "nombre" : "Dersa detergente bicarbinato en polvo 4 kilogramos",
        "popular" : "no",
        "precio" : 20000,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/Dersa%20detergente%20bicarbinato%20en%20polvo%204%20kilogramos.jpg"
      },
      "-MCgznxvNSe7RQ8be9Wd" : {
        "categoria" : "aseo",
        "descripcion" : "Doble poder 1000 gramos ariel",
        "existencia" : "disponible",
        "identificador" : "-MCgznxvNSe7RQ8be9Wd",
        "nombre" : "Ariel detergente 1 kilogramo doble poder",
        "popular" : "no",
        "precio" : 8000,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/Ariel%20detergente%201%20kilogramo%20doble%20poder.jpg"
      },
      "-MCh1NSTvXp4puPDq30_" : {
        "categoria" : "aseo",
        "descripcion" : "450 gr fab color ropa",
        "existencia" : "disponible",
        "identificador" : "-MCh1NSTvXp4puPDq30_",
        "nombre" : "Fab protección detergente color 450 gramos",
        "popular" : "no",
        "precio" : 3600,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/Fab%20protecci%C3%B3n%20detergente%20color%20450%20gramos.jpg"
      },
      "-MCh3SO1M49opTHcguQY" : {
        "categoria" : "aseo",
        "descripcion" : "X4 unidades ",
        "existencia" : "disponible",
        "identificador" : "-MCh3SO1M49opTHcguQY",
        "nombre" : "Clorox Blancox paquete paca pack bolsa blanqueador",
        "popular" : "no",
        "precio" : 3000,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/Clorox%20Blancox%20paquete%20paca%20pack%20bolsa%20blanqueador.jpg"
      },
      "-MCh42G-psDpbyauWQp5" : {
        "categoria" : "aseo",
        "descripcion" : "X24 unidades 500ml clorox",
        "existencia" : "disponible",
        "identificador" : "-MCh42G-psDpbyauWQp5",
        "nombre" : "Caja clorox blancox",
        "popular" : "no",
        "precio" : 14900,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/Caja%20clorox%20blancox.jpg"
      },
      "-MCh50k5LPFqEIOoNd_T" : {
        "categoria" : "primarios",
        "descripcion" : "X24 unidades ",
        "existencia" : "disponible",
        "identificador" : "-MCh50k5LPFqEIOoNd_T",
        "nombre" : "Paca de harina de trigo toñita",
        "popular" : "no",
        "precio" : 28900,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/Paca%20de%20harina%20de%20trigo%20to%C3%B1ita.jpg"
      },
      "-MCh5jt4UEr9SlqiN9Gb" : {
        "categoria" : "primarios",
        "descripcion" : "X24 unidades harina arepa repa",
        "existencia" : "disponible",
        "identificador" : "-MCh5jt4UEr9SlqiN9Gb",
        "nombre" : "Paca harina arepa repa",
        "popular" : "no",
        "precio" : 32500,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/Paca%20harina%20arepa%20repa.jpg"
      },
      "-MCh7MLD3UfXczRlS3nc" : {
        "categoria" : "primarios",
        "descripcion" : "X24 unidades trigo harina la nieve",
        "existencia" : "disponible",
        "identificador" : "-MCh7MLD3UfXczRlS3nc",
        "nombre" : "Paca harina de trigo la nieve",
        "popular" : "no",
        "precio" : 27900,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/Paca%20harina%20de%20trigo%20la%20nieve.jpg"
      },
      "-MChAjrcLVYXxcgcMEmi" : {
        "categoria" : "salud & belleza",
        "descripcion" : "1000 ml alcohol San martin",
        "existencia" : "disponible",
        "identificador" : "-MChAjrcLVYXxcgcMEmi",
        "nombre" : "Alcohol 1 litro ",
        "popular" : "no",
        "precio" : 7900,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/Alcohol%201%20litro%20.jpg"
      },
      "-MChB-SkfGjBD3LSLvmN" : {
        "categoria" : "salud & belleza",
        "descripcion" : "750 ml alcohol San martin",
        "existencia" : "disponible",
        "identificador" : "-MChB-SkfGjBD3LSLvmN",
        "nombre" : "Alcohol 750 ml San martin",
        "popular" : "no",
        "precio" : 5400,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/Alcohol%20750%20ml.jpg"
      },
      "-MD5L7nA1VGx5wQHlp3W" : {
        "categoria" : "primarios",
        "descripcion" : "Arroz Leopardo tipo Gourmet paca x 25 unidades ",
        "existencia" : "disponible",
        "identificador" : "-MD5L7nA1VGx5wQHlp3W",
        "nombre" : "Arroz Leopardo paca x 25 und",
        "popular" : "no",
        "precio" : 38900,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.amazonaws.com/Arroz%20Leopardo%20paca%20x%2025%20und.jpg"
      },
      "-MD5RBTF8sPtTVs1wqgg" : {
        "categoria" : "carnes",
        "descripcion" : "Libra de hueso carnudo",
        "existencia" : "disponible",
        "identificador" : "-MD5RBTF8sPtTVs1wqgg",
        "nombre" : "Hueso Carnudo ",
        "popular" : "no",
        "precio" : 1800,
        "tipo" : "pesado",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/Hueso%20Carnudo%20.jpg"
      },
      "-MD5S5uzfu38i31wKPIC" : {
        "categoria" : "carnes",
        "descripcion" : "Hueso de res x libra",
        "existencia" : "disponible",
        "identificador" : "-MD5S5uzfu38i31wKPIC",
        "nombre" : "Hueso",
        "popular" : "no",
        "precio" : 1500,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/Hueso.jpg"
      },
      "-MDUnFI66LBjeHj8c724" : {
        "categoria" : "primarios",
        "descripcion" : "Cartón de huevos kikes x 30 + paca de arroz Mi Arroz x 25 libras + aceite Don F 2 litros",
        "existencia" : "disponible",
        "identificador" : "-MDUnFI66LBjeHj8c724",
        "nombre" : "Promoción Huevos + Arroz + Aceite",
        "popular" : "no",
        "precio" : 54900,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.amazonaws.com/Promoci%C3%B3n%20Huevos%20%2B%20Arroz%20%2B%20Aceite.jpg"
      },
      "-MDV08ROPiXsPWG1Qqql" : {
        "categoria" : "primarios",
        "descripcion" : "Paca de arroz Sabroson x 25 libras + Garrafa de aceite Don F x 2 litros ",
        "existencia" : "disponible",
        "identificador" : "-MDV08ROPiXsPWG1Qqql",
        "nombre" : "COMBO Arroz + Aceite",
        "popular" : "no",
        "precio" : 49800,
        "tipo" : "unitario",
        "urlImagen" : "https://prodsbucket.s3.amazonaws.com/COMBO%20Arroz%20%2B%20Aceite.jpg"
      },
      "-ME002FhbzhHsNA1tWi4" : {
        "categoria" : "carnes",
        "descripcion" : "Mojarra Negra fresca x 1 libra",
        "existencia" : "no disponible",
        "identificador" : "-ME002FhbzhHsNA1tWi4",
        "nombre" : "Mojarra Negra x 500 gr",
        "popular" : "si",
        "precio" : 4900,
        "tipo" : "pesado",
        "urlImagen" : "https://prodsbucket.s3.sa-east-1.amazonaws.com/-ME002FhbzhHsNA1tWi4IMG-20200805-WA0009.jpg"
      }
}